Distributions:
    - name: centos
      release: 6
      
      build_cmd:
      - make all

    - name: ubuntu
      release: 14.04
      
      build_cmd:
      - make all

    - name: ubuntu
      release: 12.04
      
      build_cmd:
      - make all

Package:
    build_env: go