Distributions:
    - name: centos
      release: 6
      build_cmd:
      - make .build

    - name: ubuntu
      release: 14.04
      build_cmd:
      - make .build

    - name: ubuntu
      release: 12.04
      build_cmd:
      - go get -d -v ./...
      - go install -v ./...
      - ls -la ../../../../
      - ls -la ../../../../bin
      - mkdir -p ./build/metrilyx-cacher/opt/metrilyx/bin
      - cp ../../../../bin/metrilyx-cacher ./build/metrilyx-cacher/opt/metrilyx/bin/

Package:
    build_env: go